Traceback (most recent call last):
  File "/home/ubuntu/WorkSpace/FlaskChatGPT/venv/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ubuntu/WorkSpace/FlaskChatGPT/venv/lib/python3.10/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ubuntu/WorkSpace/FlaskChatGPT/venv/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/WorkSpace/FlaskChatGPT/venv/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/WorkSpace/FlaskChatGPT/venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/WorkSpace/FlaskChatGPT/venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/ubuntu/WorkSpace/FlaskChatGPT/app.py", line 11, in index
    return render_template('index.html')
  File "/home/ubuntu/WorkSpace/FlaskChatGPT/venv/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/ubuntu/WorkSpace/FlaskChatGPT/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/ubuntu/WorkSpace/FlaskChatGPT/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/ubuntu/WorkSpace/FlaskChatGPT/venv/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ubuntu/WorkSpace/FlaskChatGPT/venv/lib/python3.10/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ubuntu/WorkSpace/FlaskChatGPT/venv/lib/python3.10/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ubuntu/WorkSpace/FlaskChatGPT/venv/lib/python3.10/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html


openai.error.AuthenticationError: Incorrect API key provided: sk-aggk4***************************************6tvq. You can find your API key at https://platform.openai.com/account/api-keys.
